docs_dir: docs/
repo_url: https://github.com/cloud-bulldozer/kube-burner
nav:
- Home: index.md
- How to guide: 
  - CLI: cli.md
  - Configuration: configuration.md
  - Measurements: measurements.md
  - Metrics: metrics.md
  - Indexers: indexers.md
  - Alerting: alerting.md
- Development:
  - Contributing: contributing.md
  - Authors: authors.md
site_name: Kube-burner
markdown_extensions:
- toc:
    permalink: "#"
theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 4
  hljs_languages:
  - yaml
  - golang
